rvm:
  - 2.2.2
  - 2.1.0
  - 2.0.0-p481
before_install:
  - gem update --system
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
script: "bundle exec rspec spec/"
branches:
  only:
    - master
    - best_practices
